// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.28.3
// source: buy.proto

package buy

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BuyV1Client is the client API for BuyV1 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BuyV1Client interface {
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error)
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
}

type buyV1Client struct {
	cc grpc.ClientConnInterface
}

func NewBuyV1Client(cc grpc.ClientConnInterface) BuyV1Client {
	return &buyV1Client{cc}
}

func (c *buyV1Client) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	out := new(CreateResponse)
	err := c.cc.Invoke(ctx, "/api.book_store.v1.BuyV1/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *buyV1Client) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, "/api.book_store.v1.BuyV1/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BuyV1Server is the server API for BuyV1 service.
// All implementations must embed UnimplementedBuyV1Server
// for forward compatibility
type BuyV1Server interface {
	Create(context.Context, *CreateRequest) (*CreateResponse, error)
	Get(context.Context, *GetRequest) (*GetResponse, error)
	mustEmbedUnimplementedBuyV1Server()
}

// UnimplementedBuyV1Server must be embedded to have forward compatible implementations.
type UnimplementedBuyV1Server struct {
}

func (UnimplementedBuyV1Server) Create(context.Context, *CreateRequest) (*CreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedBuyV1Server) Get(context.Context, *GetRequest) (*GetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedBuyV1Server) mustEmbedUnimplementedBuyV1Server() {}

// UnsafeBuyV1Server may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BuyV1Server will
// result in compilation errors.
type UnsafeBuyV1Server interface {
	mustEmbedUnimplementedBuyV1Server()
}

func RegisterBuyV1Server(s grpc.ServiceRegistrar, srv BuyV1Server) {
	s.RegisterService(&BuyV1_ServiceDesc, srv)
}

func _BuyV1_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BuyV1Server).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.book_store.v1.BuyV1/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BuyV1Server).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BuyV1_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BuyV1Server).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.book_store.v1.BuyV1/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BuyV1Server).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BuyV1_ServiceDesc is the grpc.ServiceDesc for BuyV1 service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BuyV1_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.book_store.v1.BuyV1",
	HandlerType: (*BuyV1Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _BuyV1_Create_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _BuyV1_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "buy.proto",
}
